### ISSUE TITLE
readme file

### ISSUE THREAD

**Issue by ryanrca** [zephraph/vue-theme-loader#1]
There is no difference between the before and after examples, except the after has brand2 missing.
I have no idea what this project does, nor how it helps me.

**Comment by zephraph** [comment]
Thanks for the feedback, I'll update the README.

**Comment by zephraph** [comment]
@ryanrca better?

**Comment by ryanrca** [comment]
A little bit.  But where do you set "theme"?
should this:
```
          { 
            loader: 'vue-theme-loader',
            options: {
              theme: 'test1'
            }
          }
```
be this:
```
          { 
            loader: 'vue-theme-loader',
            options: {
              theme: 'brand1'
            }
          }
```
The last sentence helps a little bit.  But I still have no way to know how to work this.

**Comment by zephraph** [comment]
Yeah, I can update that for consistency sake. I'm not sure what more information to give.

So, imagine this. You have multiple css files that you want to generate, but the components themselves don't differ from a markup/logic perspective. This gives you the ability to generate multiple different css payloads. 

You might, for instance, have a light and dark theme for your website. You'd run the webpack build once with `vue-theme-loader`'s theme option set to `light`. Then you'd run it again with the theme option set to `dark`. 

Inside your components you'd have styled blocks with theme attributes set. 

Imagine a single file component with these style blocks

```vue
<style>
  // shared styles here
</style>
<style theme="light">
  // light theme styles here
</style>
<style theme="dark">
  // dark theme styles here
</style>
``` 

When you build the light theme you get shared sites and light theme styles. 

Does that help?

**Comment by zephraph** [comment]
I guess we're good now? If you need anything else, let me know.
