### ISSUE TITLE
How to use in practice?

### ISSUE THREAD

**Issue by diego-lipinski-de-castro** [zephraph/vue-theme-loader#8]
Ok so, you create the multiple styles with different themes and update the webpack config and after? What should I do, what should i expect? How do I use it in practice?

**Comment by zephraph** [comment]
Let's say you had two branded sites that you were building. 

To use this plugin you unfortunately need to run a build for each brand. Anyway, there are many ways you can do that, but [webpack 3.1.0+ offers a simple solution](https://webpack.js.org/configuration/configuration-types/#exporting-multiple-configurations) or you could use something like [parallel-webpack](https://github.com/trivago/parallel-webpack). 

Your config would look something like...

```javascript
module.exports = [{
  // ... rest of brand1 config
  module: {
    rules: [
      {
        test: /\.vue$/,
        use: [
          {
            loader: 'vue-loader'
          },
          {
            loader: 'vue-theme-loader',
            options: {
              theme: 'brand1'
            }
          }
        ]
      }
    ]
  }
}, {
  // ... rest of brand2 config
  module: {
    rules: [
      {
        test: /\.vue$/,
        use: [
          {
            loader: 'vue-loader'
          },
          {
            loader: 'vue-theme-loader',
            options: {
              theme: 'brand2'
            }
          }
        ]
      }
    ]
  }
}]
```

Then you have a component with multiple themes. 

```vue
<template>
  <h1>Test</h1>
</template>

<!-- This style block would be included w/ all builds -->
<style scoped>
  h1 {
    font-size: 24px;
  }
</style>

<!-- This style block would only be included w/ brand1 build -->
<style theme="brand1" scoped>
  h1 {
    color: red;
  }
</style>

<!-- This style block would only be included w/ brand2 build -->
<style theme="brand2" scoped>
  h1 {
    color: blue;
  }
</style>
```

Essentially each brand would have its own resultant styles. Any style block that doesn't have a theme associated with it would be shared by all brand stylesheets. If there was a theme attribute then only that particular brand stylesheet would get those styles. 

Make sense?

**Comment by diego-lipinski-de-castro** [comment]
Actually it makes sense, but i still have a question, how it does it? Like, renders like 

`h1 {
   color: red
}
h1 .brand1 {
   color: blue
}
`

This way? or I'm really wrong?

I though it would be something i could use like with a directive, let's say, I have theme="theme1", i though i could use like `<nav theme="theme1"></nav>` or something like this.

**Comment by zephraph** [comment]
No, it doesn't render it. At compile time it strips out the styles that are for different themes. This plugin is specifically for developing multi-site branding, not component themes.

**Comment by diego-lipinski-de-castro** [comment]
Ok, i think i got it, i will give it a shot, thanks
